version: '3'
services:
  mysql:
    image: mysql:8
    container_name: re-logging-mysql
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: relogging
