name: develop branch CI

on:
 push:
   branches: [ "develop", release-** ]
 pull_request:
   branches: [ "develop", release-** ]
   types: [ "opened", "reopened", "synchronize", "closed" ]

permissions:
  contents: read

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Style check
      run: |  
        ./gradlew spotlessCheck

  build:
    runs-on: ubuntu-latest

    env:
      MYSQL_DATABASE: ${{ secrets.LOCAL_MYSQL_DATABASE }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.LOCAL_MYSQL_ROOT_PASSWORD }}
      DATASOURCE_URL: ${{ secrets.LOCAL_DATASOURCE_URL }}
      DATASOURCE_USERNAME: ${{ secrets.LOCAL_DATASOURCE_USERNAME }}
      DATASOURCE_PASSWORD: ${{ secrets.LOCAL_DATASOURCE_PASSWORD }}
      

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Docker
      run: docker compose up -d

    - name: Grant execute permission
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Test with Gradle
      run: ./gradlew test
